### ISSUE TITLE
Please help spread the word

### ISSUE THREAD

**Issue by RusskijKorablIdiNaxuj** [abagayev/stop-russia#57]
Hi,
I'm also working on a tool that can help choke the propaganda, however, I'm trying to share it anonymously and having a hard time.
Would you be so kind and look at this https://github.com/RusskijKorablIdiNaxuj/RusskijKorablIdiNaxuj repo and perhaps share on the channels you have access to?

Many many thanks!

**Comment by aoaoemoji** [comment]
Cyberattacks shouldn't be used to do bad things, or do things they shouldn't, patriotism is understandable, but please don't maliciously incite popular sentiment

**Comment by RusskijKorablIdiNaxuj** [comment]
Could you please clarify where is the malicious intent?

**Comment by aoaoemoji** [comment]
At least I don't think we should be participants in this war. I hope someone won't die on the battlefield because of the so-called "rational approach"

**Comment by aoaoemoji** [comment]
I am very grateful to you for your words and relevant efforts. I believe there is no problem in your position. I simply believe that the war can not make it more complicated. The casualties and losses caused by this are huge. I am very disgusted with Western forces pointing fingers at the Ukrainian government, interfering in internal affairs and provoking disputes, It is inhumane to continue to provide weapons to Ukraine and Zelensky to let more civilians participate in the battle. Civilians who take up arms will become targets. This is only bloodshed and sacrifice. We'd better be able to distinguish whether what we want to do and say will have serious consequences on the Internet. I only look at it from a human perspective. We should all be neutral! Only in this way can we contribute to solving the war. I hope you can agree with me!

**Comment by bunyk** [comment]
> I am very disgusted with Western forces pointing fingers at the Ukrainian government, interfering in internal affairs and provoking disputes, It is inhumane to continue to provide weapons to Ukraine and Zelensky to let more civilians participate in the battle.

And what is your opinion on russian powers shelling Kyiv right now? Is it humane? 

What you suggest to people in Kyiv? Just become neutral, and wait until they are sent to concentration camp somewhere in siberia? What if they don't want soviet union again?

**Comment by abagayev** [comment]
This is not the place for a fight. Russia must be stopped. Over.
